/* Decision PDF export using jsPDF. Renders single A4 page. */

(function () {
  function exportDecisionPDF(state) {
    if (!window.jspdf || !window.jspdf.jsPDF) {
      alert('jsPDF library not loaded.');
      return;
    }
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    let y = 40;

    doc.setFontSize(18).setFont(undefined, 'bold');
    doc.text('Underwriter Agent — Decision Memo', 40, y);
    y += 24;

    doc.setFontSize(9).setFont(undefined, 'normal').setTextColor(120);
    doc.text(`Generated ${new Date().toLocaleString()}`, 40, y);
    y += 28;

    const colors = {
      APPROVED: [16, 185, 129],
      CONDITIONAL_APPROVAL: [245, 158, 11],
      DENIED: [239, 68, 68],
    };
    const c = colors[state.decision] || [128, 128, 128];
    doc.setFillColor(c[0], c[1], c[2]);
    doc.rect(40, y, 515, 36, 'F');
    doc.setTextColor(255).setFontSize(18).setFont(undefined, 'bold');
    doc.text((state.decision || '').replace('_', ' '), 50, y + 24);
    if (state.risk_score != null) {
      doc.text(`Risk ${state.risk_score}/100`, 460, y + 24);
    }
    y += 56;

    doc.setTextColor(40).setFontSize(11).setFont(undefined, 'normal');
    const memoLines = doc.splitTextToSize(state.memo || '', 515);
    doc.text(memoLines, 40, y);
    y += memoLines.length * 14 + 16;

    doc.setFont(undefined, 'bold').setFontSize(12);
    doc.text('Agent Findings', 40, y);
    y += 18;
    doc.setFont(undefined, 'normal').setFontSize(10);
    for (const [name, output] of Object.entries(state.agent_outputs || {})) {
      let summary = '';
      try {
        const raw = output && output[`${name}_analysis`];
        if (raw) summary = (JSON.parse(raw).summary || '');
      } catch (_) {}
      doc.setFont(undefined, 'bold').text(name.toUpperCase(), 40, y);
      doc.setFont(undefined, 'normal');
      const lines = doc.splitTextToSize(summary, 470);
      doc.text(lines, 95, y);
      y += Math.max(14, lines.length * 12) + 6;
    }

    if (state.cost) {
      y += 10;
      doc.setFontSize(9).setTextColor(120);
      doc.text(
        `Total cost: $${state.cost.total_usd.toFixed(4)} (${state.cost.total_tokens} tokens)`,
        40, y
      );
    }

    doc.setFontSize(8).setTextColor(150);
    doc.text('Generated by github.com/alanvaa06/Underwriting_Agent', 40, 820);

    doc.save(`underwriting-decision-${Date.now()}.pdf`);
  }

  window.UnderwriterPDF = { exportDecisionPDF };
})();
